### ISSUE TITLE
using setGlobalEachLevelOptions discards message 

### ISSUE THREAD

**Issue by fref** [try0/wicket-iziToast#1]
if I set, for instance, a specific ToastOption for error message to have them displayed without timeout, using setGlobalEachLevelOptions, the message gets erased.

```java
	public Toast setToastOption(IToastOption option) {
		this.option = Args.notNull(option, "option");
		return this;
	}
```
should probably use option.overwrite() to merge the options with the per-level defaults and the message.

**Comment by try0** [comment]
Thank you for your feedback.
You're right.

I will fix in a few days!

**Comment by fref** [comment]
Thank you. It's a very nice integration.

**Comment by try0** [comment]
I have fixed and released.
You should be able to update in a matter of hours.
Please update version to 0.3.1

if you still have problems, please reopen this issue.

Thanks @fref .

**Comment by fref** [comment]
arigato gozaimashita

**Comment by try0** [comment]
douitashimasite! You are welcome.
